### ISSUE TITLE
Will the JOSN data exported after using block container extension be wrapped in a block container, causing JOSN to become bloated?

### ISSUE THREAD

**Issue by xiangshu233** [liting-yes/note-editor#2]
![image](https://github.com/litingyes/note-editor/assets/49575330/20ddbbb3-2c10-455d-8fc0-93b0eb610cac)

This will cause the json data to be unintuitive

```js
  const content = [
    {
      block:{
        // ...node
      }
      block:{
        // ...node
      }
      block:{
        // ...node
      }
      //...
    }
  ]
```

**Comment by litingyes** [comment]
What does it mean? Do you want to remove the block layer of json structure?

**Comment by litingyes** [comment]
I've been spending some time researching best practices: https://github.com/vueditor/rich-text-editor
